//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildTerraDashboard.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WildTerraDashboard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a harvest_list.txt.
        /// </summary>
        internal static string Dialog_DefaultFile_HarvestList {
            get {
                return ResourceManager.GetString("Dialog_DefaultFile_HarvestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a new_route.txt.
        /// </summary>
        internal static string Dialog_DefaultFile_Route {
            get {
                return ResourceManager.GetString("Dialog_DefaultFile_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a safe_list.txt.
        /// </summary>
        internal static string Dialog_DefaultFile_SafeList {
            get {
                return ResourceManager.GetString("Dialog_DefaultFile_SafeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a `Route file.
        /// </summary>
        internal static string Dialog_Filter_RouteFile {
            get {
                return ResourceManager.GetString("Dialog_Filter_RouteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a `Safe List.
        /// </summary>
        internal static string Dialog_Filter_SafeList {
            get {
                return ResourceManager.GetString("Dialog_Filter_SafeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a `Text files.
        /// </summary>
        internal static string Dialog_Filter_TextFiles {
            get {
                return ResourceManager.GetString("Dialog_Filter_TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Route file|*.txt.
        /// </summary>
        internal static string Filter_RouteFile {
            get {
                return ResourceManager.GetString("Filter_RouteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Safe list|*.txt.
        /// </summary>
        internal static string Filter_SafeList {
            get {
                return ResourceManager.GetString("Filter_SafeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Text files|*.txt.
        /// </summary>
        internal static string Filter_TextFiles {
            get {
                return ResourceManager.GetString("Filter_TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a River.
        /// </summary>
        internal static string FishingSpot_Default {
            get {
                return ResourceManager.GetString("FishingSpot_Default", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Route File|*.txt.
        /// </summary>
        internal static string Form1DialogFilterRouteFile {
            get {
                return ResourceManager.GetString("Form1DialogFilterRouteFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Safe List|*.txt.
        /// </summary>
        internal static string Form1DialogFilterSafeList {
            get {
                return ResourceManager.GetString("Form1DialogFilterSafeList", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Text Files|*.txt.
        /// </summary>
        internal static string Form1DialogFilterTextFiles {
            get {
                return ResourceManager.GetString("Form1DialogFilterTextFiles", resourceCulture);
            }
        }

        internal static string Form1ContextAddToDrop {
            get {
                return ResourceManager.GetString("Form1ContextAddToDrop", resourceCulture);
            }
        }

        internal static string Form1ContextAddToFood {
            get {
                return ResourceManager.GetString("Form1ContextAddToFood", resourceCulture);
            }
        }

        internal static string Form1ContextAddToSafeList {
            get {
                return ResourceManager.GetString("Form1ContextAddToSafeList", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error: {0}.
        /// </summary>
        internal static string Form1MessageErrorFormat {
            get {
                return ResourceManager.GetString("Form1MessageErrorFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill in Rod, Bait and Location!.
        /// </summary>
        internal static string Form1MessageFillRodBaitAndLocation {
            get {
                return ResourceManager.GetString("Form1MessageFillRodBaitAndLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill in the X and Z coordinates!.
        /// </summary>
        internal static string Form1MessageFillXAndZ {
            get {
                return ResourceManager.GetString("Form1MessageFillXAndZ", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter the main Follow Heal skill..
        /// </summary>
        internal static string Form1MessageFollowHealRequiresMainSkill {
            get {
                return ResourceManager.GetString("Form1MessageFollowHealRequiresMainSkill", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Follow Heal mode can only be used when the target mode is PLAYER_BY_NAME..
        /// </summary>
        internal static string Form1MessageFollowHealRequiresPlayerByName {
            get {
                return ResourceManager.GetString("Form1MessageFollowHealRequiresPlayerByName", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter at least one target name to use Follow Heal..
        /// </summary>
        internal static string Form1MessageFollowHealRequiresTargetName {
            get {
                return ResourceManager.GetString("Form1MessageFollowHealRequiresTargetName", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value of 'Resume healing above (%)' must be greater than 'Use self-heal below (%)'..
        /// </summary>
        internal static string Form1MessageHealResumeMustBeGreater {
            get {
                return ResourceManager.GetString("Form1MessageHealResumeMustBeGreater", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saved!.
        /// </summary>
        internal static string Form1MessageSaved {
            get {
                return ResourceManager.GetString("Form1MessageSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop the Fishing Bot first!.
        /// </summary>
        internal static string Form1MessageStopFishingBeforeMainBot {
            get {
                return ResourceManager.GetString("Form1MessageStopFishingBeforeMainBot", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop the Main Bot before starting Fishing!.
        /// </summary>
        internal static string Form1MessageStopMainBotBeforeFishing {
            get {
                return ResourceManager.GetString("Form1MessageStopMainBotBeforeFishing", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop recording first!.
        /// </summary>
        internal static string Form1MessageStopRecordingBeforeMainBot {
            get {
                return ResourceManager.GetString("Form1MessageStopRecordingBeforeMainBot", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop Training mode before starting Fishing!.
        /// </summary>
        internal static string Form1MessageStopTrainingBeforeFishing {
            get {
                return ResourceManager.GetString("Form1MessageStopTrainingBeforeFishing", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop Training mode before starting Heal..
        /// </summary>
        internal static string Form1MessageStopTrainingBeforeHeal {
            get {
                return ResourceManager.GetString("Form1MessageStopTrainingBeforeHeal", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop Training mode before starting the Main Bot..
        /// </summary>
        internal static string Form1MessageStopTrainingBeforeMainBot {
            get {
                return ResourceManager.GetString("Form1MessageStopTrainingBeforeMainBot", resourceCulture);
            }
        }

        internal static string Form1ButtonRecordRoute {
            get {
                return ResourceManager.GetString("Form1ButtonRecordRoute", resourceCulture);
            }
        }

        internal static string Form1ButtonStartBot {
            get {
                return ResourceManager.GetString("Form1ButtonStartBot", resourceCulture);
            }
        }

        internal static string Form1ButtonStartFishing {
            get {
                return ResourceManager.GetString("Form1ButtonStartFishing", resourceCulture);
            }
        }

        internal static string Form1ButtonStartHeal {
            get {
                return ResourceManager.GetString("Form1ButtonStartHeal", resourceCulture);
            }
        }

        internal static string Form1ButtonStopBot {
            get {
                return ResourceManager.GetString("Form1ButtonStopBot", resourceCulture);
            }
        }

        internal static string Form1ButtonStopFishing {
            get {
                return ResourceManager.GetString("Form1ButtonStopFishing", resourceCulture);
            }
        }

        internal static string Form1ButtonStopHeal {
            get {
                return ResourceManager.GetString("Form1ButtonStopHeal", resourceCulture);
            }
        }

        internal static string Form1ButtonStopRecording {
            get {
                return ResourceManager.GetString("Form1ButtonStopRecording", resourceCulture);
            }
        }

        internal static string Form1ButtonSynced {
            get {
                return ResourceManager.GetString("Form1ButtonSynced", resourceCulture);
            }
        }

        internal static string Form1CoordXFormat {
            get {
                return ResourceManager.GetString("Form1CoordXFormat", resourceCulture);
            }
        }

        internal static string Form1CoordYFormat {
            get {
                return ResourceManager.GetString("Form1CoordYFormat", resourceCulture);
            }
        }

        internal static string Form1CoordZFormat {
            get {
                return ResourceManager.GetString("Form1CoordZFormat", resourceCulture);
            }
        }

        internal static string Form1HealStatusOff {
            get {
                return ResourceManager.GetString("Form1HealStatusOff", resourceCulture);
            }
        }

        internal static string Form1HealStatusOn {
            get {
                return ResourceManager.GetString("Form1HealStatusOn", resourceCulture);
            }
        }

        internal static string Form1TrainingStatusOff {
            get {
                return ResourceManager.GetString("Form1TrainingStatusOff", resourceCulture);
            }
        }

        internal static string Form1TrainingStatusOn {
            get {
                return ResourceManager.GetString("Form1TrainingStatusOn", resourceCulture);
            }
        }

        internal static string Form1TrainingInfoExclusiveMode {
            get {
                return ResourceManager.GetString("Form1TrainingInfoExclusiveMode", resourceCulture);
            }
        }

        internal static string Form1TrainingMessageStopRouteRecordingBeforeTraining {
            get {
                return ResourceManager.GetString("Form1TrainingMessageStopRouteRecordingBeforeTraining", resourceCulture);
            }
        }

        internal static string Form1TrainingLogActivatedPrefix {
            get {
                return ResourceManager.GetString("Form1TrainingLogActivatedPrefix", resourceCulture);
            }
        }

        internal static string Form1TrainingLogDeactivated {
            get {
                return ResourceManager.GetString("Form1TrainingLogDeactivated", resourceCulture);
            }
        }

        internal static string Form1TrainingButtonStop {
            get {
                return ResourceManager.GetString("Form1TrainingButtonStop", resourceCulture);
            }
        }

        internal static string Form1TrainingButtonStart {
            get {
                return ResourceManager.GetString("Form1TrainingButtonStart", resourceCulture);
            }
        }

        internal static string Form1TrainingLogAutoEatSynced {
            get {
                return ResourceManager.GetString("Form1TrainingLogAutoEatSynced", resourceCulture);
            }
        }

        internal static string Form1TrainingLogFishingDisabledForTraining {
            get {
                return ResourceManager.GetString("Form1TrainingLogFishingDisabledForTraining", resourceCulture);
            }
        }

        internal static string Form1TrainingLogHealDisabledForTraining {
            get {
                return ResourceManager.GetString("Form1TrainingLogHealDisabledForTraining", resourceCulture);
            }
        }

        internal static string Form1TrainingLogTamingDisabledForTraining {
            get {
                return ResourceManager.GetString("Form1TrainingLogTamingDisabledForTraining", resourceCulture);
            }
        }

        internal static string Form1TamingMessageStopTrainingBeforeTaming {
            get {
                return ResourceManager.GetString("Form1TamingMessageStopTrainingBeforeTaming", resourceCulture);
            }
        }

        internal static string Form1TamingMessageStopMainBotBeforeTaming {
            get {
                return ResourceManager.GetString("Form1TamingMessageStopMainBotBeforeTaming", resourceCulture);
            }
        }

        internal static string Form1TamingMessageStopFishingBeforeTaming {
            get {
                return ResourceManager.GetString("Form1TamingMessageStopFishingBeforeTaming", resourceCulture);
            }
        }

        internal static string Form1TamingMessageStopRouteRecordingBeforeTaming {
            get {
                return ResourceManager.GetString("Form1TamingMessageStopRouteRecordingBeforeTaming", resourceCulture);
            }
        }

        internal static string Form1TamingMessageLoadRouteBeforeTaming {
            get {
                return ResourceManager.GetString("Form1TamingMessageLoadRouteBeforeTaming", resourceCulture);
            }
        }

        internal static string Form1TamingMessageFillTrapName {
            get {
                return ResourceManager.GetString("Form1TamingMessageFillTrapName", resourceCulture);
            }
        }

        internal static string Form1TamingMessageFillAtLeastOneTarget {
            get {
                return ResourceManager.GetString("Form1TamingMessageFillAtLeastOneTarget", resourceCulture);
            }
        }

        internal static string Form1TamingMessageFillCombatWeaponForAggressiveMode {
            get {
                return ResourceManager.GetString("Form1TamingMessageFillCombatWeaponForAggressiveMode", resourceCulture);
            }
        }

        internal static string Form1TamingButtonStop {
            get {
                return ResourceManager.GetString("Form1TamingButtonStop", resourceCulture);
            }
        }

        internal static string Form1TamingButtonStart {
            get {
                return ResourceManager.GetString("Form1TamingButtonStart", resourceCulture);
            }
        }

        internal static string Form1TamingLogStandaloneModeConfigSentFormat {
            get {
                return ResourceManager.GetString("Form1TamingLogStandaloneModeConfigSentFormat", resourceCulture);
            }
        }

        internal static string Form1InspectMessageFillPlayerName {
            get {
                return ResourceManager.GetString("Form1InspectMessageFillPlayerName", resourceCulture);
            }
        }

        internal static string Form1InspectLogRequestedFormat {
            get {
                return ResourceManager.GetString("Form1InspectLogRequestedFormat", resourceCulture);
            }
        }

        internal static string Form1InspectLogCollectingDataFormat {
            get {
                return ResourceManager.GetString("Form1InspectLogCollectingDataFormat", resourceCulture);
            }
        }

        internal static string Form1InspectLogNoDataReceived {
            get {
                return ResourceManager.GetString("Form1InspectLogNoDataReceived", resourceCulture);
            }
        }

        internal static string Form1InspectLogFileSavedFormat {
            get {
                return ResourceManager.GetString("Form1InspectLogFileSavedFormat", resourceCulture);
            }
        }

        internal static string Form1InspectLogSaveFailedFormat {
            get {
                return ResourceManager.GetString("Form1InspectLogSaveFailedFormat", resourceCulture);
            }
        }

        internal static string Form1InspectMessageSaveFailedFormat {
            get {
                return ResourceManager.GetString("Form1InspectMessageSaveFailedFormat", resourceCulture);
            }
        }

        internal static string Form1InspectMessageBoxTitle {
            get {
                return ResourceManager.GetString("Form1InspectMessageBoxTitle", resourceCulture);
            }
        }

        internal static string Form1InspectUnknownError {
            get {
                return ResourceManager.GetString("Form1InspectUnknownError", resourceCulture);
            }
        }

        internal static string Form1InspectLogErrorFormat {
            get {
                return ResourceManager.GetString("Form1InspectLogErrorFormat", resourceCulture);
            }
        }

        internal static string RouteRecorderLogRecordingStartedFormat {
            get {
                return ResourceManager.GetString("RouteRecorderLogRecordingStartedFormat", resourceCulture);
            }
        }

        internal static string RouteRecorderLogWalkToTraceRoute {
            get {
                return ResourceManager.GetString("RouteRecorderLogWalkToTraceRoute", resourceCulture);
            }
        }

        internal static string RouteRecorderLogErrorFormat {
            get {
                return ResourceManager.GetString("RouteRecorderLogErrorFormat", resourceCulture);
            }
        }

        internal static string RouteRecorderLogRecordingFinished {
            get {
                return ResourceManager.GetString("RouteRecorderLogRecordingFinished", resourceCulture);
            }
        }

        internal static string RouteRecorderLogPointAddedFormat {
            get {
                return ResourceManager.GetString("RouteRecorderLogPointAddedFormat", resourceCulture);
            }
        }

        internal static string RouteRecorderLogSaveErrorFormat {
            get {
                return ResourceManager.GetString("RouteRecorderLogSaveErrorFormat", resourceCulture);
            }
        }

        internal static string BotMountLogSystemStatusFormat {
            get {
                return ResourceManager.GetString("BotMountLogSystemStatusFormat", resourceCulture);
            }
        }

        internal static string BotMountStatusEnabled {
            get {
                return ResourceManager.GetString("BotMountStatusEnabled", resourceCulture);
            }
        }

        internal static string BotMountStatusDisabled {
            get {
                return ResourceManager.GetString("BotMountStatusDisabled", resourceCulture);
            }
        }

        internal static string BotTamingLogNoRouteLoaded {
            get {
                return ResourceManager.GetString("BotTamingLogNoRouteLoaded", resourceCulture);
            }
        }

        internal static string BotTamingLogStartedFormat {
            get {
                return ResourceManager.GetString("BotTamingLogStartedFormat", resourceCulture);
            }
        }

        internal static string BotTamingLogStopped {
            get {
                return ResourceManager.GetString("BotTamingLogStopped", resourceCulture);
            }
        }

        internal static string TrainingModeValidateEnableAtLeastOneBlock {
            get {
                return ResourceManager.GetString("TrainingModeValidateEnableAtLeastOneBlock", resourceCulture);
            }
        }

        internal static string TrainingModeValidateSkillsBlockEmpty {
            get {
                return ResourceManager.GetString("TrainingModeValidateSkillsBlockEmpty", resourceCulture);
            }
        }

        internal static string TrainingModeValidateBuffItemsBlockEmpty {
            get {
                return ResourceManager.GetString("TrainingModeValidateBuffItemsBlockEmpty", resourceCulture);
            }
        }

        internal static string TrainingModeValidateRecoveryItemsInvalidFormat {
            get {
                return ResourceManager.GetString("TrainingModeValidateRecoveryItemsInvalidFormat", resourceCulture);
            }
        }

        internal static string TrainingModeValidateAutoAttackTargetEmpty {
            get {
                return ResourceManager.GetString("TrainingModeValidateAutoAttackTargetEmpty", resourceCulture);
            }
        }

        internal static string BotMovementLogStartedWithUnstuck {
            get {
                return ResourceManager.GetString("BotMovementLogStartedWithUnstuck", resourceCulture);
            }
        }

        internal static string BotMovementLogEmptyRouteError {
            get {
                return ResourceManager.GetString("BotMovementLogEmptyRouteError", resourceCulture);
            }
        }

        internal static string BotMovementLogStopped {
            get {
                return ResourceManager.GetString("BotMovementLogStopped", resourceCulture);
            }
        }

        internal static string BotMovementLogRouteLoadedFormat {
            get {
                return ResourceManager.GetString("BotMovementLogRouteLoadedFormat", resourceCulture);
            }
        }

        internal static string BotMovementLogErrorFormat {
            get {
                return ResourceManager.GetString("BotMovementLogErrorFormat", resourceCulture);
            }
        }

        internal static string BotMovementLogUnstuckNoProgressFormat {
            get {
                return ResourceManager.GetString("BotMovementLogUnstuckNoProgressFormat", resourceCulture);
            }
        }

        internal static string BotMovementLogUnstuckTooManySkips {
            get {
                return ResourceManager.GetString("BotMovementLogUnstuckTooManySkips", resourceCulture);
            }
        }

        internal static string BotMovementLogUnstuckStuckSkippingPointFormat {
            get {
                return ResourceManager.GetString("BotMovementLogUnstuckStuckSkippingPointFormat", resourceCulture);
            }
        }

        internal static string BotHarvestLogListUpdatedFormat {
            get {
                return ResourceManager.GetString("BotHarvestLogListUpdatedFormat", resourceCulture);
            }
        }

        internal static string BotHarvestLogItemBlacklistedNoToolFormat {
            get {
                return ResourceManager.GetString("BotHarvestLogItemBlacklistedNoToolFormat", resourceCulture);
            }
        }

        internal static string BotHarvestLogWorldIdCooldownReasonSuffixFormat {
            get {
                return ResourceManager.GetString("BotHarvestLogWorldIdCooldownReasonSuffixFormat", resourceCulture);
            }
        }

        internal static string BotHarvestLogWorldIdCooldownFormat {
            get {
                return ResourceManager.GetString("BotHarvestLogWorldIdCooldownFormat", resourceCulture);
            }
        }

        internal static string BotHarvestLogBlacklistClearedNewItemsDetected {
            get {
                return ResourceManager.GetString("BotHarvestLogBlacklistClearedNewItemsDetected", resourceCulture);
            }
        }

        internal static string RadarTypeMonsterAggressive {
            get {
                return ResourceManager.GetString("RadarTypeMonsterAggressive", resourceCulture);
            }
        }

        internal static string RadarTypeMonster {
            get {
                return ResourceManager.GetString("RadarTypeMonster", resourceCulture);
            }
        }

        internal static string RadarTypeResource {
            get {
                return ResourceManager.GetString("RadarTypeResource", resourceCulture);
            }
        }

        internal static string RadarTypeDrop {
            get {
                return ResourceManager.GetString("RadarTypeDrop", resourceCulture);
            }
        }

        internal static string RadarTypeLoot {
            get {
                return ResourceManager.GetString("RadarTypeLoot", resourceCulture);
            }
        }

        internal static string RadarTypePlayer {
            get {
                return ResourceManager.GetString("RadarTypePlayer", resourceCulture);
            }
        }

        internal static string Form1WindowTitleWithPortsFormat {
            get {
                return ResourceManager.GetString("Form1WindowTitleWithPortsFormat", resourceCulture);
            }
        }

        internal static string Form1LogBagFull {
            get {
                return ResourceManager.GetString("Form1LogBagFull", resourceCulture);
            }
        }

        internal static string Form1LogBotStarted {
            get {
                return ResourceManager.GetString("Form1LogBotStarted", resourceCulture);
            }
        }

        internal static string Form1LogBotStopped {
            get {
                return ResourceManager.GetString("Form1LogBotStopped", resourceCulture);
            }
        }

        internal static string Form1LogDepositFinished {
            get {
                return ResourceManager.GetString("Form1LogDepositFinished", resourceCulture);
            }
        }

        internal static string Form1LogErrorFormat {
            get {
                return ResourceManager.GetString("Form1LogErrorFormat", resourceCulture);
            }
        }

        internal static string Form1LogFillXAndZ {
            get {
                return ResourceManager.GetString("Form1LogFillXAndZ", resourceCulture);
            }
        }

        internal static string Form1LogFishingDisabled {
            get {
                return ResourceManager.GetString("Form1LogFishingDisabled", resourceCulture);
            }
        }

        internal static string Form1LogFishingHarvestListSentFormat {
            get {
                return ResourceManager.GetString("Form1LogFishingHarvestListSentFormat", resourceCulture);
            }
        }

        internal static string Form1LogFishingHarvestListSyncedFormat {
            get {
                return ResourceManager.GetString("Form1LogFishingHarvestListSyncedFormat", resourceCulture);
            }
        }

        internal static string Form1LogFishingStartingFormat {
            get {
                return ResourceManager.GetString("Form1LogFishingStartingFormat", resourceCulture);
            }
        }

        internal static string Form1LogHarvestStatusFormat {
            get {
                return ResourceManager.GetString("Form1LogHarvestStatusFormat", resourceCulture);
            }
        }

        internal static string Form1LogHealAutoEatSynced {
            get {
                return ResourceManager.GetString("Form1LogHealAutoEatSynced", resourceCulture);
            }
        }

        internal static string Form1LogHealDisabled {
            get {
                return ResourceManager.GetString("Form1LogHealDisabled", resourceCulture);
            }
        }

        internal static string Form1LogHealEnabled {
            get {
                return ResourceManager.GetString("Form1LogHealEnabled", resourceCulture);
            }
        }

        internal static string Form1LogHunterStatusFormat {
            get {
                return ResourceManager.GetString("Form1LogHunterStatusFormat", resourceCulture);
            }
        }

        internal static string Form1LogMissingToolFormat {
            get {
                return ResourceManager.GetString("Form1LogMissingToolFormat", resourceCulture);
            }
        }

        internal static string Form1LogNavigationMovingAway {
            get {
                return ResourceManager.GetString("Form1LogNavigationMovingAway", resourceCulture);
            }
        }

        internal static string Form1LogReachedCabinStartingDeposit {
            get {
                return ResourceManager.GetString("Form1LogReachedCabinStartingDeposit", resourceCulture);
            }
        }

        internal static string Form1LogRequirementMetFormat {
            get {
                return ResourceManager.GetString("Form1LogRequirementMetFormat", resourceCulture);
            }
        }

        internal static string Form1LogReturningHomeFormat {
            get {
                return ResourceManager.GetString("Form1LogReturningHomeFormat", resourceCulture);
            }
        }

        internal static string Form1LogUdpStartedFormat {
            get {
                return ResourceManager.GetString("Form1LogUdpStartedFormat", resourceCulture);
            }
        }

        internal static string Form1LogSendingManualMountCommand {
            get {
                return ResourceManager.GetString("Form1LogSendingManualMountCommand", resourceCulture);
            }
        }

        internal static string Form1LogHealWeaponNameRequired {
            get {
                return ResourceManager.GetString("Form1LogHealWeaponNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [ALERT] Missing tool for {0}..
        /// </summary>
        internal static string Log_Alert_MissingTool {
            get {
                return ResourceManager.GetString("Log_Alert_MissingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error: {0}.
        /// </summary>
        internal static string Log_Error {
            get {
                return ResourceManager.GetString("Log_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [ERROR] Fill in coordinates X and Z!.
        /// </summary>
        internal static string Log_Error_FillCoordsXZ {
            get {
                return ResourceManager.GetString("Log_Error_FillCoordsXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [FISHING] System disabled..
        /// </summary>
        internal static string Log_Fishing_Disabled {
            get {
                return ResourceManager.GetString("Log_Fishing_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [FISHING] Starting... Spot: {0}, Bait: {1}.
        /// </summary>
        internal static string Log_Fishing_Starting {
            get {
                return ResourceManager.GetString("Log_Fishing_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Harvest: {0}.
        /// </summary>
        internal static string Log_HarvestStatus {
            get {
                return ResourceManager.GetString("Log_HarvestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hunter: {0}.
        /// </summary>
        internal static string Log_HunterStatus {
            get {
                return ResourceManager.GetString("Log_HunterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [NAVIGATION] Moving away....
        /// </summary>
        internal static string Log_Navigation_MovingAway {
            get {
                return ResourceManager.GetString("Log_Navigation_MovingAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [SYSTEM] Reached the Cabin. Starting deposit....
        /// </summary>
        internal static string Log_System_ArrivedCabinDeposit {
            get {
                return ResourceManager.GetString("Log_System_ArrivedCabinDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [SYSTEM] BAG FULL! Going to the Cabin....
        /// </summary>
        internal static string Log_System_BagFullGoingCabin {
            get {
                return ResourceManager.GetString("Log_System_BagFullGoingCabin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [SYSTEM] Bot started..
        /// </summary>
        internal static string Log_System_BotStarted {
            get {
                return ResourceManager.GetString("Log_System_BotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [SYSTEM] Bot stopped..
        /// </summary>
        internal static string Log_System_BotStopped {
            get {
                return ResourceManager.GetString("Log_System_BotStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [SYSTEM] Deposit finished..
        /// </summary>
        internal static string Log_System_DepositFinished {
            get {
                return ResourceManager.GetString("Log_System_DepositFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [SYSTEM] Requirement met: {0}.
        /// </summary>
        internal static string Log_System_RequirementMet {
            get {
                return ResourceManager.GetString("Log_System_RequirementMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [TEST] Returning Home ({0}, {1})....
        /// </summary>
        internal static string Log_Test_ReturningHome {
            get {
                return ResourceManager.GetString("Log_Test_ReturningHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [TEST] Sending manual Mount command....
        /// </summary>
        internal static string Log_Test_SendingMount {
            get {
                return ResourceManager.GetString("Log_Test_SendingMount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UDP started..
        /// </summary>
        internal static string Log_UdpStarted {
            get {
                return ResourceManager.GetString("Log_UdpStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error: {0}.
        /// </summary>
        internal static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill in coordinates X and Z!.
        /// </summary>
        internal static string Msg_FillCoordsXZ {
            get {
                return ResourceManager.GetString("Msg_FillCoordsXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill Rod, Bait and Spot!.
        /// </summary>
        internal static string Msg_FillRodBaitSpot {
            get {
                return ResourceManager.GetString("Msg_FillRodBaitSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saved!.
        /// </summary>
        internal static string Msg_Saved {
            get {
                return ResourceManager.GetString("Msg_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop the Fishing Bot first!.
        /// </summary>
        internal static string Msg_StopFishingFirst {
            get {
                return ResourceManager.GetString("Msg_StopFishingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop the Main Bot before starting Fishing!.
        /// </summary>
        internal static string Msg_StopMainBotBeforeFishing {
            get {
                return ResourceManager.GetString("Msg_StopMainBotBeforeFishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop recording first!.
        /// </summary>
        internal static string Msg_StopRecordingFirst {
            get {
                return ResourceManager.GetString("Msg_StopRecordingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a X: {0}.
        /// </summary>
        internal static string Ui_CoordX {
            get {
                return ResourceManager.GetString("Ui_CoordX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Y: {0}.
        /// </summary>
        internal static string Ui_CoordY {
            get {
                return ResourceManager.GetString("Ui_CoordY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Z: {0}.
        /// </summary>
        internal static string Ui_CoordZ {
            get {
                return ResourceManager.GetString("Ui_CoordZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Listening....
        /// </summary>
        internal static string Ui_Listening {
            get {
                return ResourceManager.GetString("Ui_Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OFF.
        /// </summary>
        internal static string Ui_Off {
            get {
                return ResourceManager.GetString("Ui_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ON.
        /// </summary>
        internal static string Ui_On {
            get {
                return ResourceManager.GetString("Ui_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RECORD ROUTE.
        /// </summary>
        internal static string Ui_RecordRoute {
            get {
                return ResourceManager.GetString("Ui_RecordRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a START BOT.
        /// </summary>
        internal static string Ui_StartBot {
            get {
                return ResourceManager.GetString("Ui_StartBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a START FISHING.
        /// </summary>
        internal static string Ui_StartFishing {
            get {
                return ResourceManager.GetString("Ui_StartFishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a STOP BOT.
        /// </summary>
        internal static string Ui_StopBot {
            get {
                return ResourceManager.GetString("Ui_StopBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a STOP FISHING.
        /// </summary>
        internal static string Ui_StopFishing {
            get {
                return ResourceManager.GetString("Ui_StopFishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a STOP RECORDING.
        /// </summary>
        internal static string Ui_StopRecording {
            get {
                return ResourceManager.GetString("Ui_StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Synced.
        /// </summary>
        internal static string Ui_Synced {
            get {
                return ResourceManager.GetString("Ui_Synced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UDP started..
        /// </summary>
        internal static string Ui_UdpStarted {
            get {
                return ResourceManager.GetString("Ui_UdpStarted", resourceCulture);
            }
        }
    }
}
