//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildTerraDashboard.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WildTerraDashboard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a harvest_list.txt.
        /// </summary>
        internal static string Dialog_DefaultFile_HarvestList {
            get {
                return ResourceManager.GetString("Dialog_DefaultFile_HarvestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a new_route.txt.
        /// </summary>
        internal static string Dialog_DefaultFile_Route {
            get {
                return ResourceManager.GetString("Dialog_DefaultFile_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a safe_list.txt.
        /// </summary>
        internal static string Dialog_DefaultFile_SafeList {
            get {
                return ResourceManager.GetString("Dialog_DefaultFile_SafeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a `Route file.
        /// </summary>
        internal static string Dialog_Filter_RouteFile {
            get {
                return ResourceManager.GetString("Dialog_Filter_RouteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a `Safe List.
        /// </summary>
        internal static string Dialog_Filter_SafeList {
            get {
                return ResourceManager.GetString("Dialog_Filter_SafeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a `Text files.
        /// </summary>
        internal static string Dialog_Filter_TextFiles {
            get {
                return ResourceManager.GetString("Dialog_Filter_TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Route file|*.txt.
        /// </summary>
        internal static string Filter_RouteFile {
            get {
                return ResourceManager.GetString("Filter_RouteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Safe list|*.txt.
        /// </summary>
        internal static string Filter_SafeList {
            get {
                return ResourceManager.GetString("Filter_SafeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Text files|*.txt.
        /// </summary>
        internal static string Filter_TextFiles {
            get {
                return ResourceManager.GetString("Filter_TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a River.
        /// </summary>
        internal static string FishingSpot_Default {
            get {
                return ResourceManager.GetString("FishingSpot_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [ALERT] Missing tool for {0}..
        /// </summary>
        internal static string Log_Alert_MissingTool {
            get {
                return ResourceManager.GetString("Log_Alert_MissingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error: {0}.
        /// </summary>
        internal static string Log_Error {
            get {
                return ResourceManager.GetString("Log_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [ERROR] Fill in coordinates X and Z!.
        /// </summary>
        internal static string Log_Error_FillCoordsXZ {
            get {
                return ResourceManager.GetString("Log_Error_FillCoordsXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [FISHING] System disabled..
        /// </summary>
        internal static string Log_Fishing_Disabled {
            get {
                return ResourceManager.GetString("Log_Fishing_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [FISHING] Starting... Spot: {0}, Bait: {1}.
        /// </summary>
        internal static string Log_Fishing_Starting {
            get {
                return ResourceManager.GetString("Log_Fishing_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Harvest: {0}.
        /// </summary>
        internal static string Log_HarvestStatus {
            get {
                return ResourceManager.GetString("Log_HarvestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hunter: {0}.
        /// </summary>
        internal static string Log_HunterStatus {
            get {
                return ResourceManager.GetString("Log_HunterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [NAVIGATION] Moving away....
        /// </summary>
        internal static string Log_Navigation_MovingAway {
            get {
                return ResourceManager.GetString("Log_Navigation_MovingAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [SYSTEM] Reached the Cabin. Starting deposit....
        /// </summary>
        internal static string Log_System_ArrivedCabinDeposit {
            get {
                return ResourceManager.GetString("Log_System_ArrivedCabinDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [SYSTEM] BAG FULL! Going to the Cabin....
        /// </summary>
        internal static string Log_System_BagFullGoingCabin {
            get {
                return ResourceManager.GetString("Log_System_BagFullGoingCabin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [SYSTEM] Bot started..
        /// </summary>
        internal static string Log_System_BotStarted {
            get {
                return ResourceManager.GetString("Log_System_BotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [SYSTEM] Bot stopped..
        /// </summary>
        internal static string Log_System_BotStopped {
            get {
                return ResourceManager.GetString("Log_System_BotStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [SYSTEM] Deposit finished..
        /// </summary>
        internal static string Log_System_DepositFinished {
            get {
                return ResourceManager.GetString("Log_System_DepositFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [SYSTEM] Requirement met: {0}.
        /// </summary>
        internal static string Log_System_RequirementMet {
            get {
                return ResourceManager.GetString("Log_System_RequirementMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [TEST] Returning Home ({0}, {1})....
        /// </summary>
        internal static string Log_Test_ReturningHome {
            get {
                return ResourceManager.GetString("Log_Test_ReturningHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [TEST] Sending manual Mount command....
        /// </summary>
        internal static string Log_Test_SendingMount {
            get {
                return ResourceManager.GetString("Log_Test_SendingMount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UDP started..
        /// </summary>
        internal static string Log_UdpStarted {
            get {
                return ResourceManager.GetString("Log_UdpStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error: {0}.
        /// </summary>
        internal static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill in coordinates X and Z!.
        /// </summary>
        internal static string Msg_FillCoordsXZ {
            get {
                return ResourceManager.GetString("Msg_FillCoordsXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill Rod, Bait and Spot!.
        /// </summary>
        internal static string Msg_FillRodBaitSpot {
            get {
                return ResourceManager.GetString("Msg_FillRodBaitSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saved!.
        /// </summary>
        internal static string Msg_Saved {
            get {
                return ResourceManager.GetString("Msg_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop the Fishing Bot first!.
        /// </summary>
        internal static string Msg_StopFishingFirst {
            get {
                return ResourceManager.GetString("Msg_StopFishingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop the Main Bot before starting Fishing!.
        /// </summary>
        internal static string Msg_StopMainBotBeforeFishing {
            get {
                return ResourceManager.GetString("Msg_StopMainBotBeforeFishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop recording first!.
        /// </summary>
        internal static string Msg_StopRecordingFirst {
            get {
                return ResourceManager.GetString("Msg_StopRecordingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a X: {0}.
        /// </summary>
        internal static string Ui_CoordX {
            get {
                return ResourceManager.GetString("Ui_CoordX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Y: {0}.
        /// </summary>
        internal static string Ui_CoordY {
            get {
                return ResourceManager.GetString("Ui_CoordY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Z: {0}.
        /// </summary>
        internal static string Ui_CoordZ {
            get {
                return ResourceManager.GetString("Ui_CoordZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Listening....
        /// </summary>
        internal static string Ui_Listening {
            get {
                return ResourceManager.GetString("Ui_Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OFF.
        /// </summary>
        internal static string Ui_Off {
            get {
                return ResourceManager.GetString("Ui_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ON.
        /// </summary>
        internal static string Ui_On {
            get {
                return ResourceManager.GetString("Ui_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RECORD ROUTE.
        /// </summary>
        internal static string Ui_RecordRoute {
            get {
                return ResourceManager.GetString("Ui_RecordRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a START BOT.
        /// </summary>
        internal static string Ui_StartBot {
            get {
                return ResourceManager.GetString("Ui_StartBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a START FISHING.
        /// </summary>
        internal static string Ui_StartFishing {
            get {
                return ResourceManager.GetString("Ui_StartFishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a STOP BOT.
        /// </summary>
        internal static string Ui_StopBot {
            get {
                return ResourceManager.GetString("Ui_StopBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a STOP FISHING.
        /// </summary>
        internal static string Ui_StopFishing {
            get {
                return ResourceManager.GetString("Ui_StopFishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a STOP RECORDING.
        /// </summary>
        internal static string Ui_StopRecording {
            get {
                return ResourceManager.GetString("Ui_StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Synced.
        /// </summary>
        internal static string Ui_Synced {
            get {
                return ResourceManager.GetString("Ui_Synced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UDP started..
        /// </summary>
        internal static string Ui_UdpStarted {
            get {
                return ResourceManager.GetString("Ui_UdpStarted", resourceCulture);
            }
        }
    }
}
